# Generated by Django 4.2.6 on 2023-11-10 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from database.models import UserRolesField


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatmapMetadata",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("difficulty", models.CharField(max_length=256)),
                ("ar", models.FloatField()),
                ("od", models.FloatField()),
                ("cs", models.FloatField()),
                ("hp", models.FloatField()),
                ("length", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BeatmapsetMetadata",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("artist", models.CharField(max_length=256)),
                ("title", models.CharField(max_length=256)),
                ("cover", models.CharField(max_length=256)),
                ("creator", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Mappool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="MappoolConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_override", models.CharField(max_length=32, null=True)),
                (
                    "mappool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_connections",
                        to="database.mappool",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField(max_length=8, null=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(default="", max_length=256)),
                ("link", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentInvolvement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roles", UserRolesField(default=0)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="involved_users",
            field=models.ManyToManyField(
                through="database.TournamentInvolvement", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="mappools",
            field=models.ManyToManyField(
                through="database.MappoolConnection", to="database.mappool"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MappoolFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mappool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.mappool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mappoolconnection",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mappool_connections",
                to="database.tournament",
            ),
        ),
        migrations.CreateModel(
            name="MappoolBeatmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mods", models.CharField(max_length=8)),
                ("star_rating", models.FloatField()),
                ("rating_color", models.CharField(max_length=7)),
                (
                    "beatmap_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mappool_beatmaps",
                        to="database.beatmapmetadata",
                    ),
                ),
                (
                    "beatmapset_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mappool_beatmaps",
                        to="database.beatmapsetmetadata",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mappool",
            name="beatmaps",
            field=models.ManyToManyField(
                related_name="mappools", to="database.mappoolbeatmap"
            ),
        ),
        migrations.AddField(
            model_name="mappool",
            name="favorites",
            field=models.ManyToManyField(
                related_name="mappool_favorites",
                through="database.MappoolFavorite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mappool",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_mappools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
