# Generated by Django 5.0.6 on 2024-09-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappoolbeatmapconnection',
            old_name='beatmaps',
            new_name='beatmap',
        ),
    ]
