# Generated by Django 4.2.6 on 2023-12-09 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mappoolbeatmap",
            old_name="mods",
            new_name="slot",
        ),
    ]
