# Generated by Django 4.2.6 on 2023-12-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_rename_mods_mappoolbeatmap_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappoolbeatmap",
            name="mods",
            field=models.CharField(default="", max_length=23),
            preserve_default=False,
        ),
    ]
