# Generated by Django 5.0.6 on 2024-09-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_beatmaps_mappoolbeatmapconnection_beatmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmapmod',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
