# Generated by Django 5.0.6 on 2024-09-13 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_beatmapmod_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournamentinvolvement',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='tournamentinvolvement_unique_constraint'),
        ),
    ]
