# Generated by Django 4.2.6 on 2024-02-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_mappoolbeatmap_mods"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatmapMod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField(max_length=2)),
                ("settings", models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name="mappoolbeatmap",
            name="mods",
        ),
        migrations.AddField(
            model_name="mappoolbeatmap",
            name="mods",
            field=models.ManyToManyField(
                related_name="related_beatmaps", to="database.beatmapmod"
            ),
        ),
    ]
