# Generated by Django 4.2.6 on 2024-02-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_beatmapmod_remove_mappoolbeatmap_mods_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mappoolbeatmap",
            name="rating_color",
        ),
        migrations.AlterField(
            model_name="beatmapmod",
            name="settings",
            field=models.JSONField(null=True),
        ),
    ]
