# Generated by Django 5.0.6 on 2024-09-13 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_tournamentinvolvement_tournamentinvolvement_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinvolvement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to=settings.AUTH_USER_MODEL),
        ),
    ]
