# Generated by Django 4.2.6 on 2024-02-29 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_remove_mappoolbeatmap_rating_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beatmapmod",
            old_name="abbreviation",
            new_name="acronym",
        ),
    ]
