# Generated by Django 5.0.6 on 2024-09-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_tournamentfavorite_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoolfavorite',
            name='mappool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_connections', to='database.mappool'),
        ),
    ]
