# Generated by Django 4.2.6 on 2024-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0006_rename_abbreviation_beatmapmod_acronym"),
    ]

    operations = [
        migrations.AddField(
            model_name="beatmapmetadata",
            name="bpm",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
