# Generated by Django 5.0.6 on 2024-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_beatmapmetadata_bpm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beatmapmetadata',
            old_name='bpm',
            new_name='bpm_min',
        ),
        migrations.AddField(
            model_name='beatmapmetadata',
            name='bpm_max',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
