# Generated by Django 5.0.6 on 2024-07-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_bpm_beatmapmetadata_bpm_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beatmapmetadata',
            old_name='bpm_min',
            new_name='bpm',
        ),
        migrations.RemoveField(
            model_name='beatmapmetadata',
            name='bpm_max',
        ),
    ]
