# Generated by Django 5.0.6 on 2024-09-15 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_mappoolfavorite_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoolfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappool_favorite_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_favorite_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
