# Generated by Django 5.0.6 on 2024-09-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_mappoolfavorite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappool',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
