# Generated by Django 5.0.6 on 2024-07-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_bpm_min_beatmapmetadata_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoolfavorite',
            name='timestamp',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
