# Generated by Django 5.0.6 on 2024-08-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_mappoolfavorite_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappool',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
