# Generated by Django 5.2 on 2025-05-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0011_alter_mappool_submitted_by_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mappoolconnection",
            constraint=models.UniqueConstraint(
                fields=("tournament", "mappool"),
                name="mappoolconnection_unique_constraint",
            ),
        ),
    ]
