# Generated by Django 5.0.6 on 2024-08-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_mappool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='abbreviation',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='link',
            field=models.CharField(default='', max_length=256),
        ),
    ]
