# Generated by Django 5.2 on 2025-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0012_mappoolconnection_mappoolconnection_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mappool",
            name="description",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="mappool",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="mappoolbeatmapconnection",
            name="slot",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
