# Generated by Django 5.0.6 on 2024-08-10 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_tournament_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinvolvement',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvements', to='database.tournament'),
        ),
    ]
