# Generated by Django 5.0.6 on 2024-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_tournamentinvolvement_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='abbreviation',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
