# Generated by Django 5.0.6 on 2024-08-23 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_tournamentfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='favorites',
            field=models.ManyToManyField(related_name='tournament_favorites', through='database.TournamentFavorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
