# Generated by Django 5.0.6 on 2024-08-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_tournament_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
