# Generated by Django 5.0.6 on 2024-08-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappool',
            name='avg_star_rating',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
