# Generated by Django 5.0.6 on 2024-08-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_mappool_avg_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatmapsetmetadata',
            name='cover',
        ),
    ]
