# Generated by Django 4.2.6 on 2023-11-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OsuUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.PositiveIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=15)),
                ("avatar", models.CharField(max_length=256)),
                ("cover", models.CharField(max_length=256)),
                ("auth_token", models.CharField(max_length=256, null=True)),
                ("refresh_token", models.CharField(max_length=256, null=True)),
                ("refresh_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
