# Generated by Django 4.2.6 on 2023-12-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="osuuser",
            name="auth_token",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="osuuser",
            name="avatar",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="osuuser",
            name="cover",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="osuuser",
            name="refresh_token",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
