# Generated by Django 5.0.6 on 2024-07-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_osuuser_auth_token_alter_osuuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osuuser',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='osuuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='osuuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='osuuser',
            name='refresh_at',
        ),
        migrations.RemoveField(
            model_name='osuuser',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='osuuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='osuuser',
            name='avatar',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='osuuser',
            name='cover',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='osuuser',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
