# Generated by Django 5.0.6 on 2024-10-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trafficstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLFuncMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('last_state', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
